FROM maven:3.9.9-eclipse-temurin-21-alpine AS build
WORKDIR /workspace
COPY pom.xml .
RUN mvn -B -q dependency:go-offline
COPY src src
RUN mvn -B -q -DskipTests package

FROM eclipse-temurin:25-jre-alpine
RUN addgroup -S orderflow && adduser -S orderflow -G orderflow
WORKDIR /app
COPY --from=build /workspace/target/orderflow-api-*.jar app.jar
USER orderflow
EXPOSE 8080
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75.0", "-jar", "/app/app.jar"]
